// <auto-generated />
using System;
using AgOpenNtripCaster.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgOpenNtripCaster.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429011524_AddPassiveRoverDiagnostics")]
    partial class AddPassiveRoverDiagnostics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MountPointId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MountPointId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.CasterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultAuthentication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultCompression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultCountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DefaultFeeRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("DefaultGenerator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultNetwork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FallbackHost")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<int>("NmeaSupport")
                        .HasColumnType("integer");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CasterInfos");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.ClientSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("text");

                    b.Property<string>("ClientUserAgent")
                        .HasColumnType("text");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisconnectReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstGgaAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GgaFrameCount")
                        .HasColumnType("integer");

                    b.Property<int>("InvalidGgaFrameCount")
                        .HasColumnType("integer");

                    b.Property<double?>("LastAccuracy")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastAltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastDifferentialAgeSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("LastDifferentialStationId")
                        .HasColumnType("text");

                    b.Property<int?>("LastFixQuality")
                        .HasColumnType("integer");

                    b.Property<double?>("LastGeoidSeparationMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastHdop")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastPositionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastSatelliteCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastStreamPauseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MountPointId")
                        .HasColumnType("integer");

                    b.Property<int>("PeakPendingBufferCount")
                        .HasColumnType("integer");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StalePositionPeriods")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("StreamPausedSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAt");

                    b.HasIndex("MountPointId");

                    b.HasIndex("UserId", "ConnectedAt");

                    b.ToTable("ClientSessions");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.DiagnosticEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientSessionId")
                        .HasColumnType("text");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MountPointId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SourceConnectionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientSessionId");

                    b.HasIndex("Kind");

                    b.HasIndex("MountPointId");

                    b.HasIndex("SourceConnectionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("DiagnosticEvents");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.EmailSmtpSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableTls")
                        .HasColumnType("boolean");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailSmtpSettings");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.EmailTriggerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminEmailForSourceNotifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SendSourceOfflineEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("SendSourceOnlineEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("SendVerificationEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("SendWelcomeEmail")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EmailTriggerSettings");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.MountPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Authentication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BytesPerSecond")
                        .HasColumnType("integer");

                    b.Property<int>("Carrier")
                        .HasColumnType("integer");

                    b.Property<string>("Compression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedFormat")
                        .HasColumnType("text");

                    b.Property<string>("DetectedNavSystems")
                        .HasColumnType("text");

                    b.Property<bool>("FeeRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormatDetails")
                        .HasColumnType("text");

                    b.Property<string>("Generator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRtcmMessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxClients")
                        .HasColumnType("integer");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Misc")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NavSystem")
                        .HasColumnType("text");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NmeaRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<int?>("ReferenceStationId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireClientAuthentication")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("RtcmLatitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RtcmLongitude")
                        .HasColumnType("numeric");

                    b.Property<int>("Solution")
                        .HasColumnType("integer");

                    b.Property<string>("SourcePassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("MountPoints");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.NetworkInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char>("AuthenticationRequired")
                        .HasColumnType("character(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<char>("FeeRequired")
                        .HasColumnType("character(1)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NetworkInfos");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.NtripGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NtripGroups");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.NtripUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastGeneratedSourcePassword")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SourcePassword")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SourcePasswordGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.PerformanceMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveClients")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveSources")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveZeroCopyBuffers")
                        .HasColumnType("integer");

                    b.Property<double>("AverageBroadcastTimeMs")
                        .HasColumnType("double precision");

                    b.Property<long>("GcCollectionCount")
                        .HasColumnType("bigint");

                    b.Property<long>("MemorySavedBytes")
                        .HasColumnType("bigint");

                    b.Property<double>("PeakBroadcastTimeMs")
                        .HasColumnType("double precision");

                    b.Property<int>("PeakZeroCopyBuffers")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalBroadcasts")
                        .HasColumnType("integer");

                    b.Property<long>("TotalBytesSent")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalMemoryUsageBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalMountPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.SourceConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BytesReceived")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisconnectReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRtcmAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MountPointId")
                        .HasColumnType("integer");

                    b.Property<int>("RtcmChunkCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAt");

                    b.HasIndex("MountPointId");

                    b.ToTable("SourceConnections");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.TelegramSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyErrors")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifySourceConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifySourceDisconnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifySystemStarted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TelegramSettings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MountPointNtripGroup", b =>
                {
                    b.Property<int>("AllowedGroupsId")
                        .HasColumnType("integer");

                    b.Property<int>("MountPointsId")
                        .HasColumnType("integer");

                    b.HasKey("AllowedGroupsId", "MountPointsId");

                    b.HasIndex("MountPointsId");

                    b.ToTable("GroupMountPoints", (string)null);
                });

            modelBuilder.Entity("NtripGroupNtripUser", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("integer");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserGroups", (string)null);
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.Activity", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.MountPoint", "MountPoint")
                        .WithMany()
                        .HasForeignKey("MountPointId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MountPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.ClientSession", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.MountPoint", "MountPoint")
                        .WithMany("ClientSessions")
                        .HasForeignKey("MountPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripUser", "User")
                        .WithMany("ClientSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("MountPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.DiagnosticEvent", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.ClientSession", "ClientSession")
                        .WithMany()
                        .HasForeignKey("ClientSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.MountPoint", "MountPoint")
                        .WithMany()
                        .HasForeignKey("MountPointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.SourceConnection", "SourceConnection")
                        .WithMany()
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientSession");

                    b.Navigation("MountPoint");

                    b.Navigation("SourceConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.MountPoint", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripUser", "Owner")
                        .WithMany("OwnedMountPoints")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.SourceConnection", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.MountPoint", "MountPoint")
                        .WithMany("SourceConnections")
                        .HasForeignKey("MountPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MountPoint");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MountPointNtripGroup", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripGroup", null)
                        .WithMany()
                        .HasForeignKey("AllowedGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.MountPoint", null)
                        .WithMany()
                        .HasForeignKey("MountPointsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NtripGroupNtripUser", b =>
                {
                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgOpenNtripCaster.Server.Models.Entities.NtripUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.MountPoint", b =>
                {
                    b.Navigation("ClientSessions");

                    b.Navigation("SourceConnections");
                });

            modelBuilder.Entity("AgOpenNtripCaster.Server.Models.Entities.NtripUser", b =>
                {
                    b.Navigation("ClientSessions");

                    b.Navigation("OwnedMountPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
